#!/bin/sh
# (C) MandrakeSoft
# Chmouel Boudjnah <chmouel@mandrakesoft.com>
#
# $Id: Xsetup_0,v 1.12 2005/06/12 14:35:57 flepied Exp $

if [ -x /etc/X11/xinit/fixkeyboard ]; then
    /etc/X11/xinit/fixkeyboard
fi

if [ -x /etc/X11/xinit.d/numlock ]; then
    /etc/X11/xinit.d/numlock &
fi

for i in /etc/X11/xsetup.d/*.xsetup ; do
    [ -d $i ] && continue

    if [ -x $i ]; then
	if grep -q "# to be sourced" $i; then
	    . $i
	else
	    $i &
	fi
    fi
done

if [ -f /usr/share/mdk/backgrounds/default.png ] && [ -f /usr/bin/xloadimage ]; then
	/usr/bin/xloadimage -onroot -fullscreen /usr/share/mdk/backgrounds/default.png &
fi

# Xsetup_0 ends here
